server:
  port: 18081
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
spring:
  application:
    name: dagaitem-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dagaitem-db
    password: gibgib321
    username: gibsmon
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 90000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    path: /api-doc
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method